#!/bin/bash

set -e
shopt -s extglob

version="$1"

[[ "$version" == "" ]] && echo "error: new version not specified" >&2 && exit 1

sed -i 's/dexpatcher-repo\.dexpatcher\.dexpatcher\-tool\:dexpatcher\:[^'"'"'"]*/dexpatcher-repo\.dexpatcher\.dexpatcher\-tool\:dexpatcher\:'"$version"'/g' \
        !(makeinfo.com.getid)/build.gradle
