#!/bin/bash

set -e
shopt -s extglob

version="$1"

[[ "$version" == "" ]] && echo "error: new version not specified" >&2 && exit 1

sed -i 's|//services\.gradle\.org/distributions/gradle\-.*\.zip|//services\.gradle\.org/distributions/gradle\-'"$version"'\.zip|g' \
        gradle/wrapper/gradle-wrapper.properties \
        !(makeinfo.com.getid)/gradle/wrapper/gradle-wrapper.properties
