#!/bin/bash

set -e
shopt -s extglob

version="$1"

[[ "$version" == "" ]] && echo "error: new version not specified" >&2 && exit 1

sed -i 's/com\.github\.lanchon\.dexpatcher\:dexpatcher\-gradle\:[^'"'"'"]*/com\.github\.lanchon\.dexpatcher\:dexpatcher\-gradle\:'"$version"'/g' \
        !(makeinfo.com.getid)/build.gradle
