package makeinfo.com.getid;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.ActionBarActivity;
import android.view.MenuItem;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.Toast;

import lanchon.dexpatcher.annotation.DexAdd;
import lanchon.dexpatcher.annotation.DexEdit;
import lanchon.dexpatcher.annotation.DexIgnore;
import ru.bartwell.exfilepicker.ExFilePickerActivity;

@DexEdit
public class MainActivity extends ActionBarActivity {

    @DexIgnore EditText device;
    @DexIgnore Button device_copy;
    //@DexIgnore EditText gsfid;
    //@DexIgnore Button gsf_copy;
    //@DexIgnore EditText imei;
    //@DexIgnore Button imei_copy;
    //@DexIgnore EditText imsi;
    //@DexIgnore Button imsi_copy;
    //@DexIgnore EditText sim;
    //@DexIgnore Button sim_copy;
    //@DexIgnore EditText wifi;
    //@DexIgnore Button wifi_copy;

    //@DexIgnore ImageView makeinfoapps;
    @DexIgnore boolean val;

    // A default constructor will be generated by the compiler if none is defined,
    // so define one and ignore it so that it will not get into the patched app.
    @DexIgnore
    public MainActivity() { throw null; }

    // Rename the existing onCreate method.
    @DexEdit(target = "onCreate")
    protected void source_onCreate(Bundle bundle) { throw null; }

    // Add a replacement for the renamed method.
    @DexAdd
    @Override protected void onCreate(Bundle bundle){
        // First invoke the original onCreate method.
        source_onCreate(bundle);
        // Then replace the text and handler of the device ID 'Copy' button.
        device_copy.setText("Share");
        device_copy.setOnClickListener(new DeviceCopyOnClick());
    }

    // Use a named class to avoid clashing with existing anonymous classes.
    @DexAdd
    class DeviceCopyOnClick implements View.OnClickListener {
        @Override public void onClick(View view) {
            if (MainActivity.this.val) {
                // Instead of copying the device ID, share it.
                Intent intent = new Intent(Intent.ACTION_SEND);
                intent.setType("text/plain");
                intent.putExtra(Intent.EXTRA_SUBJECT, "Device ID");
                intent.putExtra(Intent.EXTRA_TEXT, device.getText().toString());
                startActivity(Intent.createChooser(intent, "Share Device ID"));
            } else {
                Toast.makeText(MainActivity.this.getApplicationContext(), "Nothing to Share", 0).show();
            }
        }
    }

    @DexEdit(target = "onOptionsItemSelected")
    protected boolean source_onOptionsItemSelected(MenuItem item) { throw null; }

    @DexAdd
    @Override public boolean onOptionsItemSelected(MenuItem item) {
        // We imported this file chooser from the project's 'build.gradle' script:
        // -> https://github.com/bartwell/ExFilePicker
        // Let's make the 'Rate' option menu item open the file chooser.
        int id = item.getItemId();
        // Note that our dynamically generated 'R' class (hack.getid.R) includes
        // the imported resources from the source app.
        if (id == R.id.rate) {
            startActivity(new Intent(getApplicationContext(), ExFilePickerActivity.class));
            return true;
        }
        // If 'Rate' was not the selected item, delegate to the original handler.
        return source_onOptionsItemSelected(item);
    }

}
